# Generated by Django 3.0.8 on 2020-07-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_auto_20200713_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='username',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='todolistitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todoapp.TodoCategory'),
        ),
    ]
